config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/all_posts', to: 'static_pages#all_posts'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  resources :users, except: [:index, :new] do
    member do
      get :followers, :following
      get :inactive
      get :resend_activation
    end
  end

  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :account_activations, only: [:new, :edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'columns', except: %i[about contact]
  before_action :require_logged_in, only: [:all_posts]

  def home
    if logged_in?
      @post = current_user.posts.build
      @pagy, @feed_items = pagy(current_user.feed, items: 20)
      render :home
    else
      render :welcome
    end
  end

  def all_posts
    @pagy, @all_items = pagy(posts_all, items: 20)
  end

  def about; end

  def contact; end
end

app/views/static_pages/_post_form.html.haml
.row.border-bottom.p-2
  .col-2.col-lg-1
    - if post.user.avatar.attached?
      = image_tag(post.user.avatar, size: '50', class: 'rounded-circle')
    - else
      = image_tag('/images/avatar_default.png', size: '50', class: 'rounded-circle')
  .col
    = simple_form_for post do |f|
      = f.input :content, label: false, placeholder: 'Share what you think', input_html: { class: 'post-input-field fs-5' }
      .d-flex
        = f.button :submit, 'Post', class: 'btn btn-secondary ms-auto'

app/views/static_pages/_right_panel.html.haml
.d-flex.flex-column
  = link_to 'All Nanoblog posts', all_posts_url, class: 'btn btn_lg btn-outline-dark m-2'

app/views/static_pages/_welcome.html.haml
.container-fluid
  .row.full-height
    .col-lg-5.front.full-height
    .col-lg-7
      .full-height.d-flex.flex-column.justify-content-between.align-items-center
        .p-2.mt-5.d-flex.flex-column.align-items-center
          %h1.fw-bold Get straight to the point
          = link_to 'Log in', login_url, class: 'btn btn-secondary btn-lg mt-3'
        .p-2.d-flex.flex-column.align-items-center
          %p.fs-5.text-danger Haven't got an account?
          %h1.fw-bold Register now
          = link_to 'Sign up', signup_url, class: 'btn btn-secondary btn-lg mt-3'
        .p-2.nav
          = link_to 'About', about_url, class: 'nav-link link-secondary'
          = link_to 'Contact', contact_url, class: 'nav-link link-secondary'

app/views/static_pages/about.html.haml
.container.d-flex.flex-column.full-height
  %h2.fw-bold.mt-4
    About
  %p.fs-5.mt-4
    This is mini blogging application, 
    inspired by 
    #{ link_to 'Ruby on Rails Tutorial', '#', class: 'text-danger text-decoration-none' }. 
    You can see source code 
    #{link_to 'here', '#', class: 'text-danger text-decoration-none'}.
  .mt-auto.mb-3
    = render 'shared/back_link'

app/views/static_pages/all_posts.html.haml
- provide(:title, 'All posts')
= render @all_items
= raw pagy_bootstrap_nav(@pagy)

app/views/static_pages/contact.html.haml
.container.d-flex.flex-column.full-height
  %h2.fw-bold.mt-4 
    Contact
  %p.fs-5.mt-4 
    Contact me #{link_to 'here', '#', class: 'text-danger text-decoration-none'}.
  .mt-auto.mb-3
    = render 'shared/back_link'

app/views/static_pages/full.html.haml
- provide(:title, 'All posts')
= render @all_items
= raw pagy_bootstrap_nav(@pagy)

app/views/static_pages/home.html.haml
- provide(:title, 'Home')
.mb-2.mt-2.border-bottom
= render 'post_form', post: @post
.mb-2.mt-2.border-bottom
= render @feed_items
= raw pagy_bootstrap_nav(@pagy)


 

app/views/static_pages/welcome.html.haml
.container-fluid
  .row.full-height
    .col-lg-5.front.full-height
    .col-lg-7
      .full-height.d-flex.flex-column.justify-content-between.align-items-center
        .p-2.mt-5.d-flex.flex-column.align-items-center
          %h1.fw-bold Get straight to the point
          = link_to 'Log in', login_url, class: 'btn btn-secondary btn-lg mt-3'
        .p-2.d-flex.flex-column.align-items-center
          %p.fs-5.text-danger Haven't got an account?
          %h1.fw-bold Register now
          = link_to 'Sign up', signup_url, class: 'btn btn-secondary btn-lg mt-3'
        .p-2.nav
          = link_to 'About', about_url, class: 'nav-link link-secondary'
          = link_to 'Contact', contact_url, class: 'nav-link link-secondary'