config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/all_posts', to: 'static_pages#all_posts'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  resources :users, except: [:index, :new] do
    member do
      get :followers, :following
      get :inactive
      get :resend_activation
    end
  end

  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :account_activations, only: [:new, :edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  activated         :boolean          default(FALSE)
#  activated_at      :datetime
#  activation_digest :string
#  admin             :boolean          default(FALSE)
#  email             :string           not null
#  name              :string           not null
#  password_digest   :string           not null
#  remember_digest   :string
#  reset_digest      :string
#  reset_sent_at     :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#  index_users_on_name   (name) UNIQUE
#
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_create :set_activation_digest

  has_secure_password
  validates :name, presence: true, length: { in: 2..30 }, uniqueness: true
  validates :email, presence: true, uniqueness: true, email: { mode: :strict }
  validates :password, presence: true, length: { minimum: 8 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_one_attached :avatar
  has_one_attached :background_image

  has_many :posts,
           dependent: :destroy

  has_many :active_relationships,
           foreign_key: :follower_id,
           class_name: :Relationship,
           dependent: :destroy,
           inverse_of: :follower

  has_many :passive_relationships,
           foreign_key: :followed_id,
           class_name: :Relationship,
           dependent: :destroy,
           inverse_of: :followed

  has_many :followers,
           through: :passive_relationships

  has_many :following,
           through: :active_relationships,
           source: :followed

  def self.generate_token
    SecureRandom.urlsafe_base64
  end

  def self.generate_digest(string)
    BCrypt::Password.create(string)
  end

  def set_remember_digest
    self.remember_token = User.generate_token
    update(remember_digest: User.generate_digest(remember_token))
  end

  def delete_remember_digest
    self.remember_token = nil
    update(remember_digest: nil)
  end

  def authenticated?(action, token)
    digest = send("#{action}_digest") # == self.send()
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def activate!
    update(activated: true, activated_at: Time.zone.now)
  end

  def set_reset_digest
    self.reset_token = User.generate_token
    update(reset_digest: User.generate_digest(reset_token), reset_sent_at: Time.zone.now)
  end

  def delete_reset_digest
    update(reset_digest: nil, reset_sent_at: nil)
  end

  def new_activation_digest
    self.activation_token = User.generate_token
    update(activation_digest: User.generate_digest(activation_token))
  end

  def send_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
      WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                OR user_id = :user_id", user_id: id)
  end
  private

  def set_activation_digest
    self.activation_token = User.generate_token
    self.activation_digest = User.generate_digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'columns', except: [:inactive]

  before_action :require_not_logged_in, only: %i[new create inactive resend_activation]
  before_action :require_logged_in, only: %i[show following followers]
  before_action :require_owner, only: %i[edit update]
  before_action :require_owner_or_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Account activation email has been sent'
      redirect_to inactive_user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      flash[:info] = @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to root_url
  end

  def following
    @user = User.find_by(id: params[:id])
    @title = "#{@user.name} is following:"
    @related = @user.following
    render :show_follow
  end

  def followers
    @user = User.find_by(id: params[:id])
    @title = "#{@user.name}'s followers:"
    @related = @user.followers
    render :show_follow
  end

  def inactive
    @user = User.find_by(id: params[:id])
  end

  def resend_activation
    @user = User.find_by(id: params[:id])
    @user.new_activation_digest
    @user.send_activation_email
    flash[:info] = 'Account activation email has been sent'
    redirect_to inactive_user_url(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :background_image)
  end
end

app/views/users/_follow_form.html.haml
= simple_form_for :relationship, url: relationships_url do |f|
  = f.input :followed_id, label: false, input_html: { type: 'hidden', value: user.id }
  = f.button :submit, 'Follow', class: 'btn btn-secondary'

app/views/users/_unfollow_form.html.haml
- rel_id = Relationship.find_by(followed_id: user.id).id
= simple_form_for :relationship, method: :delete, url: relationship_url(rel_id) do |f|
  = f.button :submit, 'Unfollow', class: 'btn btn-outline-dark turn-red'

app/views/users/_user.html.haml
.row.border-bottom.p-2.position-relative
  .col-1
    - if user.avatar.attached?
      = image_tag(user.avatar, size: '50', class: 'rounded-circle')
    - else
      = image_tag('/images/avatar_default.png', size: '50', class: 'rounded-circle')
  .col.d-flex.flex-column
    .ps-1 
      = link_to user.name, user_url(user.id), class: 'stretched-link link-dark text-decoration-none'
    .ps-1.text-secondary
      = user.email
  - if @user == current_user
    .col-2.on-top 
      -if !current_user.following.include?(user)
        = render 'follow_form', user: user
      - else
        = render 'unfollow_form', user: user

app/views/users/_user_form.html.haml
- if user
  .m-5
.m-2
  = simple_form_for user do |f|
    %div
      = f.input :name
    .mt-3
      = f.input :email
    - if !current_user
      .mt-3
        = f.input :password
      .mt-3
        = f.input :password_confirmation
    -if current_user
      .mt-3
        = f.input :avatar, label_html: { class: 'form-label' }, input_html: { class: 'form-control'}
      .mt-3
        = f.input :background_image, label_html: { class: 'form-label' }, input_html: { class: 'form-control'}
    .mt-3
      = f.button :submit, class: 'btn btn-lg btn-secondary mt-3'
      

app/views/users/_user_info.html.haml
.align-self-end.m-3
  - if @user == current_user
    = render 'shared/edit_link'
  - else 
    -if !current_user.following.include?(@user)
      = render 'follow_form', user: @user
    - else
      = render 'unfollow_form', user: @user
.mt-2.ms-4.lh-1
  .fw-bold.fs-4 
    = @user.name
  .text-secondary.fs-5
    = @user.email
.mt-2.ms-4.text-secondary
  Joined #{time_tag @user.created_at.to_date}
.mt-2.mb-3.d-flex
  .ms-4.fw-bold
    = link_to @user.following.count, following_user_url(@user), class: 'link-dark text-decoration-none'
  .ms-1
    = link_to 'Following', following_user_url(@user), class: 'link-secondary text-decoration-none'
  .ms-4.fw-bold
    = link_to @user.followers.count, following_user_url(@user), class: 'link-dark text-decoration-none'
  .text-secondary.ms-1
    = link_to 'Followers', followers_user_url(@user), class: 'link-secondary text-decoration-none'

  

app/views/users/_user_panel.html.haml
- provide(:title, action == :show ?  @user.name : 'Edit account')
.d-flex.flex-column.border-bottom
  .four-one-ratio.position-relative
    = image_tag(@user.background_image, class: 'position-absolute top-0 cover') if @user.background_image.attached?
  .position-relative.d-flex.flex-column
    .position-absolute.top-0.start-0.translate-middle-y.rounded-circle.bg-light.ms-2
      - if @user.avatar.attached?
        = image_tag(@user.avatar, size: '150', class: 'rounded-circle p-2')
      - else
        = image_tag('/images/avatar_default.png', size: '150', class: 'rounded-circle p-2')
    = action == :show ? (render 'user_info') : (render 'user_form', user: @user)
- if !@user.posts.empty? && action == :show    
  .mb-2.mt-2.border-bottom

app/views/users/edit.html.haml
= render 'user_panel', action: :edit

app/views/users/inactive.html.haml
.container.d-flex.flex-column.full-height
  %h2.fw-bold.mt-4 
    Account not active
  %p.fs-5.mt-4 
    Hi #{@user.name}! Your account has not been activated yet. Check your email for activation link.
  .d-flex.justify-content-end.align-items-end.mt-5
    .me-3.text-danger
      Didn't get activation link?
    = link_to 'Send again', resend_activation_user_url(@user), class: 'btn btn-lg btn-outline-dark turn-red'
  .mt-auto.mb-3
    = render 'shared/back_link'

app/views/users/new.html.haml
.container.d-flex.flex-column.full-height
  .mt-3
    %h1.fw-bold Create account
  .mt-3
    = render 'user_form', user: @user
  .mt-auto.mb-3
    = render 'shared/back_link'

app/views/users/show.html.haml
= render 'user_panel', action: :show
= render @posts

app/views/users/show_follow.html.haml
- provide(:title, @title)
= render @related