config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/all_posts', to: 'static_pages#all_posts'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  resources :users, except: [:index, :new] do
    member do
      get :followers, :following
      get :inactive
      get :resend_activation
    end
  end

  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :account_activations, only: [:new, :edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_back_link.html.haml
.nav
  = link_to 'Back to Nanoblog', root_url, class: 'fs-5 nav-link, link-secondary text-decoration-none'

app/views/shared/_edit_link.html.haml
= link_to 'Edit profile', edit_user_url, class: 'btn btn-secondary'

app/views/shared/_flash.html.haml
.position-fixed.vw-100.d-flex.flex-column.on-top
  - flash.each do |category, message| 
    %div{ class: "bg-#{category} bg-gradient text-white text-center full-width p-2"}
      = message
	

app/views/shared/_logout_link.html.haml
= simple_form_for :session, method: :delete, url: logout_url  do |f|
  = f.button :submit, 'Log out'

app/views/shared/_navi.html.haml
.container.full.width.px-3
  .navbar-toggler{"aria-controls" => "#navi", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navi", "data-bs-toggle" => "collapse", type: "button"}
    %span.navbar-toggler-icon
  #navi.collapse.navbar-collapse.flex-grow-0
    .d-flex.flex-column
     
      .image.p-2
        = image_tag('/images/nblog_smaller.png', :alt => "cat")
      %ul.nav.flex-column.p-2
        %li.nav-item.main-link.p-2
          %i.bi.bi-house.fs-2
          = link_to 'Home', root_url, class: "#{current_page?(root_url) ? 'link-danger' : 'link-dark'} p-1 fs-3 fw-bold text-decoration-none"
        %li.nav-item.main-link.p-2
          %i.bi.bi-person.fs-2
          = link_to 'Profile', user_url(current_user.id), class: "#{current_page?(user_url(current_user.id)) ? 'link-danger' : 'link-dark'} p-1 fs-3 fw-bold text-decoration-none"
        %li.nav-item.main-link.d-flex.p-2
          %i.bi.bi-box-arrow-left.fs-2
          = simple_form_for :session, method: :delete, url: logout_url do |f|
            = f.button :submit, 'Logout', class: "link-dark p-1 fs-3 fw-bold"