config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/all_posts', to: 'static_pages#all_posts'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  resources :users, except: [:index, :new] do
    member do
      get :followers, :following
      get :inactive
      get :resend_activation
    end
  end

  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  resources :account_activations, only: [:new, :edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :posts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_posts_on_user_id                 (user_id)
#  index_posts_on_user_id_and_created_at  (user_id,created_at)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Post < ApplicationRecord
  default_scope { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 150 }

  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in

  def create
    @post = current_user.posts.build(post_params)
    flash[:danger] = @post.errors.full_messages.to_sentence unless @post.save
    redirect_to root_url
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id])
    if @post
      @post.destroy
      flash[:success] = 'Post has been deleted'
      redirect_to request.referer || root_url
    else
      flash[:danger] = 'You can not delete this post'
      redirect_to root_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/views/posts/_post.html.haml
.border-bottom.p-2
  .row
    .col-2.col-lg-1
      - if post.user.avatar.attached?
        = link_to image_tag(post.user.avatar, size: '50', class: 'rounded-circle'), user_url(post.user_id)
      - else
        = link_to image_tag('/images/avatar_default.png', size: '50', class: 'rounded-circle'), user_url(post.user_id)
    .col
      .d-flex.flex-wrap.justify-content-between.mb-2
        .fw-bold.mb-2
          = link_to post.user.name, user_url(post.user_id), class: 'link-dark text-decoration-none'
        .text-secondary 
          posted #{ time_ago_in_words(post.created_at) } ago
      = Rinku.auto_link(simple_format(post.content), :all, 'target="_blank"').html_safe
      .d-flex.mt-2
        .ms-auto
          = render 'posts/post_delete_link', post: post if post.user == current_user

app/views/posts/_post_delete_link.html.haml
= simple_form_for post, method: :delete, url: post_url(post)  do |f|
  = f.button :submit, 'Delete post', class: 'btn btn-sm btn-outline-dark turn-red'